---

- name: deploy php web application
  hosts: "{{ webservers }}"
  remote_user: "{{ user }}"
  pwd: "{{ ssh_pwd }}"

  tasks:
  - name: install dependencies on host
    install: 
      packages: "{{ packages }}"
      log: True

  - name: copy php application to host
    sftp:
      dst_location: "{{ web_app_dst }}"
      metadata:
        owner: "{{ web_app_owner }}"
        group: "{{ web_app_group }}"
        mode: "{{ web_app_mode }}"
      log: True