---

- name: deploy php web application
  hosts: "{{ webservers }}"
  remote_user: "{{ user }}"
  pwd: "{{ ssh_pwd }}"

  tasks:
  - name: uninstall dependencies on host
    uninstall: 
      packages: "{{ packages }}"